### PR TITLE
Add FromOCC (const TopoDS_Shape& s)

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
This will allow using Netgen together with OCCT or python bindings like [pyOCCT](https://github.com/trelau/pyOCCT) or [OCP](https://github.com/CadQuery/OCP) without writing to disk.

NB: same functionality as in  #11 
CC: @trelau

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
@JSchoeberl @mhochsteger any thoughts on this PR?

**Comment by bragostin** [comment]
That would be a very useful feature. For example I am using Netgen coupled with Cadquery and Fenics to perform automatic shape optimization and having to write and read the step file from the disk all the time is not optimal.
I found Netgen to be very efficient at meshing "organic" like structures, such as triply periodic surfaces.

**Comment by ChrLackner** [comment]
I think having a constructor is preferable.
This commit should solve the problem:
https://github.com/NGSolve/netgen/commit/fb13152004ce323353a6d5825b3fb664a22b2940

**Comment by adam-urbanczyk** [comment]
I tried to copy the existing style, but yours is better. Thanks for doing this @ChrLackner !

**Pull request closed without merging**
